| NAME               	| PROMPT                                                                                                                                                                                	| DESCRIPTION                                                                                                   	| EXAMPLE                                       	|
|--------------------	|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------	|-----------------------------------------------	|
| APP                	| kubectl ai "create deploy kbot"                                                                                                                                                       	| Generate kbot deployment yaml-file                                                                            	| /workspaces/kbot/yaml/app.yaml                	|
| APP-LIVENESSPROBE  	| kubectl ai "create deploy with livenessprobe from image gcr.io/golden-memory-383208/demo:v1.0.0"                                                                                      	| Generate app deployment yaml-file with configured livenessProbe                                               	| /workspaces/kbot/yaml/app-livenessprobe.yaml  	|
| APP-READINESSPROBE 	| kubectl ai "create deploy with readinessprobe from image gcr.io/golden-memory-383208/demo:v1.0.0"                                                                                     	| Generate app deployment yaml-file with configured readinessProbe                                              	| /workspaces/kbot/yaml/app-readinessprobe.yaml 	|
| APP-VOLUMEMOUNTS   	| kubectl ai "create deploy with readinessprobe from image gcr.io/golden-memory-383208/demo:v1.0.0 with mountpath /data and name data"                                                  	| Generate app deployment yaml-file with configured readinessProbe and mounted volume                           	| /workspaces/kbot/yaml/app-volumeMounts.yaml   	|
| APP-CRONJOB        	| kubectl ai "create cronjob with period every 10 mins, use container name job and bash command echo 10 mins passed"                                                                    	| Generate cron-job with 10 minutes period and executing bash command                                           	| /workspaces/kbot/yaml/app-cronjob.yaml        	|
| APP-JOB            	| kubectl ai "create job which backup postgesql database using pgdump and copy backup to mounted volume data-backup"                                                                    	| Backup PostgreSQL DB to mounted volume                                                                        	| /workspaces/kbot/yaml/app-job.yaml            	|
| APP-MULTICONTAINER 	| kubectl ai "create pod with containers nginx and oracle linux, using bash add to index.html info about top 3 processes with RAM utilization every 1 min"                              	| Using OracleLinux check top RAM-eaters, add information to html-file with possibility check info from browser 	| /workspaces/kbot/yaml/app-multicontainer.yaml 	|
| APP-RESOURCES      	| kubectl ai "create deploy with readinessprobe from image gcr.io/golden-memory-383208/demo:v1.0.0 allocate requested resources cpu 100m, memory 256Mi and limit cpu 100m memory 512Mi" 	| Allocate resources for deployment                                                                             	| /workspaces/kbot/yaml/app-resources.yaml      	|
| APP-SECRET-ENV     	| kubectl ai "create pod with secret username and password envs with names started SECRET"                                                                                              	| Using env with secrets                                                                                        	| /workspaces/kbot/yaml/app-secret-env.yaml     	|