apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job
              command: ["/bin/bash", "-c", "echo 10 mins passed"]
          restartPolicy: OnFailure