apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
        - name: kbot
          image: kbot:latest
          ports:
            - containerPort: 8080